// Generated by CoffeeScript 1.7.1
(function() {
  var NUM_FRAMES, featuresCtrl, minutedockr;

  minutedockr = angular.module('minutedockr', []);

  NUM_FRAMES = 4;

  featuresCtrl = function($scope, $timeout) {
    var subFrame;
    $scope.frame = 0;
    $scope.subFrame = 0;
    subFrame = function() {
      return $timeout(function() {
        $scope.subFrame += 1;
        return subFrame();
      }, 2000);
    };
    subFrame();
    $scope.next = function() {
      return $scope.frame = ($scope.frame + 1) % NUM_FRAMES;
    };
    return $scope.prev = function() {
      $scope.frame -= 1;
      if ($scope.frame < 0) {
        return $scope.frame = NUM_FRAMES - 1;
      }
    };
  };

  minutedockr.controller('featuresCtrl', ['$scope', '$timeout', featuresCtrl]);

}).call(this);
